import {
  Goal,
  LifeEvent,
  LifeState,
  Principle,
  TrajectoryPattern,
  UserPhaseMeta,
  Vision,
  DailyReview,
  TodoItem,
} from '../types';

export const INITIAL_USER_PHASE: UserPhaseMeta = {
  currentPhase: '经济自主重建期',
  mainQuest: '建立稳定现金流 (5000+/月)',
  keyRecentShift: '正在从外部评价驱动，向内部评价驱动转变',
  recentProgress: '即使关系产生波动，也越来越能够继续自己的生活',
};

export const INITIAL_VISIONS: Vision[] = [
  {
    id: 'v-1',
    title: '经济自主',
    statement: '拥有完全支配自己时间与生活的自由，拥有稳定自给的现金流与清晰资产。',
    category: 'career',
    createdAt: '2026-07-01',
  },
  {
    id: 'v-2',
    title: '身心强健',
    statement: '体魄紧致通透，能量充盈稳固，无论遇到何种风浪，肉体神殿始终是温暖的避风港。',
    category: 'health',
    createdAt: '2026-07-01',
  },
  {
    id: 'v-3',
    title: '内部自尊与独立边界',
    statement: '成为能够给自己无条件肯定的人，在关系中主动表达而不失去自我，不把自我价值建立在别人的反馈上。',
    category: 'relationship',
    createdAt: '2026-07-01',
  },
  {
    id: 'v-4',
    title: '手作与灵性创造',
    statement: '将对植物草药、仪式蜡烛、塔罗咨询的深刻理解，转化为温暖他人并持续创造复利的美好事业。',
    category: 'creation',
    createdAt: '2026-07-01',
  },
];

export const INITIAL_PRINCIPLES: Principle[] = [
  {
    id: 'p-1',
    statement: '不需要通过痛苦证明自己的价值。',
    category: '核心信念',
    why: '过去的创伤让我误以为只有受苦才算努力，真正的创造应当是顺畅而坚定的。',
    createdAt: '2026-07-01',
  },
  {
    id: 'p-2',
    statement: '不让一个人、一件事吞掉整个人生。',
    category: '边界管理',
    why: '生活是由六大领域构成的丰盛整体，任何单点的波动都不足以打翻全盘。',
    createdAt: '2026-07-01',
  },
  {
    id: 'p-3',
    statement: '不因为逃避焦虑而行动，也不因为逃避行动而追求即时舒适。',
    category: '行动指南',
    why: '在焦虑时盲目乱抓只能带来更多消耗；停留在当下，做真正有累积的事。',
    createdAt: '2026-07-01',
  },
  {
    id: 'p-4',
    statement: '可以喜欢一个人，但不为了得到爱而失去自己。',
    category: '亲密关系',
    why: '爱是两个独立主体的并肩，而非通过出卖尊严换取廉价的安全感。',
    createdAt: '2026-07-01',
  },
  {
    id: 'p-5',
    statement: '主动表达，但不负责两个人的关系。',
    category: '关系心理',
    why: '我负责真实清晰地表达我的感受与需求，对方的回应与否属于对方的课题。',
    createdAt: '2026-07-01',
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'g-1',
    title: '每月收入稳定达到 5000+',
    type: 'short_term',
    area: 'career',
    parentId: 'g-2',
    timeframeType: 'fuzzy',
    timeframeFuzzy: '三个月内 (2026 Q3-Q4)',
    startDate: '2026-07-01',
    targetDate: '2026-10-31',
    reality: '每日直播2小时、每周交付5-8单手工蜡烛/占卜咨询、定期更新手作小红书内容。',
    why: '获得基本生存安全感与经济自主权，清空负债，不再受制于任何外部评价。',
    identity: '我正在成为一个能够独立创造价值并自食其力的人。',
    coreBelief: '我不需要通过痛苦证明自己的价值，财富是我创造价值的自然副产物。',
    evidence: [
      '今天完成直播2小时，自然成交2单',
      '完成客户定制蜡烛交付1单',
      '收到老客户的主动复购推荐',
      '连续2周保持每日稳定的业务输出',
    ],
    realityEvidence: [
      {
        id: 'ev-1',
        text: '完成今日 2 小时专场直播与客户咨询互动，稳定输出业务',
        date: '2026-08-15',
        actionTaken: '直播交付',
      },
      {
        id: 'ev-2',
        text: '完成定制草药魔法蜡烛产品制作与打包寄送',
        date: '2026-08-15',
        actionTaken: '产品闭环交付',
      },
      {
        id: 'ev-3',
        text: '完成2位客户深度星盘咨询，收款596元',
        date: '2026-08-14',
        actionTaken: '高价值咨询',
      },
    ],
    spiritualManifestation: {
      practices: [
        {
          id: 'sp-1',
          type: 'candle',
          title: '点燃丰盛草药魔法蜡烛',
          detail: '点燃天然大豆草药蜡烛，在草木芳香中静心许愿，锚定自食其力的安全感与确信。',
          date: '2026-08-15',
        },
        {
          id: 'sp-2',
          type: 'affirmation',
          title: '每日核心肯定语',
          detail: '“我不需要通过痛苦证明自己的价值，财富是我创造价值的自然副产物。”',
          date: '2026-08-15',
        },
        {
          id: 'sp-3',
          type: 'angel_number',
          title: '天使数字共时性 888',
          detail: '在整理账本与订单时看到 888，象征丰盛之流正在顺畅汇聚。',
          date: '2026-08-15',
        },
      ],
      coreBeliefShifts: [
        {
          id: 'bs-1',
          oldBelief: '必须通过极度受苦和自我牺牲才能赚到干净的钱',
          newBelief: '金钱是诚实创造价值后的自然能量流动，收钱是对彼此心力的尊重',
          insight: '卸下对收费的内疚感与匮乏焦虑，把注意力放在高质量交付上。',
          date: '2026-08-12',
        },
      ],
      affirmations: [
        '我允许丰盛自然流入我的生活',
        '我所交付的每一份心力，都在为他人带来温暖与照亮',
      ],
      angelNumbers: ['888', '111'],
    },
    visionConnection: '经济自主与稳定现金流',
    manifestationNarrative: '正在从“危机与恐惧驱动”平稳转向“充盈与稳定创造”。你所付出的每一份专注，都在向宇宙发射清晰信号。',
    progressPercent: 78,
    status: 'active',
    createdAt: '2026-07-15',
  },
  {
    id: 'g-2',
    title: '清空小额负债与财务秩序建立',
    type: 'long_term',
    area: 'career',
    parentVisionId: 'v-1',
    timeframeType: 'fuzzy',
    timeframeFuzzy: '半年内',
    startDate: '2026-07-01',
    targetDate: '2026-12-31',
    reality: '每月固定结清一笔分期款项，记录每笔收支，彻底杜绝冲动情绪消费。',
    why: '彻底卸下心理沉重包袱，拥有纯净清爽的金钱能量场与选择底气。',
    identity: '我正在成为一个财务清晰、对金钱有掌控力的人。',
    coreBelief: '负债只是过去的经验数字，它无法定义我当下的价值和未来。',
    evidence: [
      '上月成功结清一笔400元的设备分期',
      '已建立连续30天不盲目消费的记录',
    ],
    realityEvidence: [
      {
        id: 'ev-201',
        text: '按时清偿本月设备分期款项 450 元',
        date: '2026-08-10',
        actionTaken: '债务削减',
      },
    ],
    spiritualManifestation: {
      practices: [
        {
          id: 'sp-201',
          type: 'visualization',
          title: '清空债务空间视觉化',
          detail: '视觉化每一笔债务归零时，金钱能量场变得明亮清爽的画面。',
          date: '2026-08-05',
        },
      ],
      coreBeliefShifts: [
        {
          id: 'bs-201',
          oldBelief: '有负债意味着我是一个失败者',
          newBelief: '负债只是过去的数字记录，现在的每一笔结清都是力量的见证',
          insight: '每一个归零的数字，都是为未来的丰盛财富腾出崭新的空间。',
          date: '2026-08-01',
        },
      ],
    },
    visionConnection: '经济自主',
    manifestationNarrative: '每一个归零的数字，都是为未来的丰盛财富腾出崭新的空间。',
    progressPercent: 45,
    status: 'active',
    createdAt: '2026-07-15',
  },
  {
    id: 'g-3',
    title: '身心能量基石重建 (运动与作息)',
    type: 'short_term',
    area: 'health',
    parentVisionId: 'v-2',
    timeframeType: 'fuzzy',
    timeframeFuzzy: '近期一个月内',
    startDate: '2026-08-01',
    targetDate: '2026-08-31',
    reality: '每周3-4次健身房力量训练与拉伸，早睡早起，保持日常活力。',
    why: '高密度的身心承载力是一切创造与表达的前提，身体是稳固一切的锚。',
    identity: '我是一个敬畏身体、懂得与精力做朋友的人。',
    coreBelief: '照顾好肉体神殿，灵性与创造力才会自由舒展。',
    evidence: [
      '本周已完成3次力量训练',
      '体态与呼吸比上个月明显更加轻盈踏实',
    ],
    realityEvidence: [
      {
        id: 'ev-301',
        text: '完成深蹲与臀腿核心力量训练 60 分钟',
        date: '2026-08-15',
        actionTaken: '力量训练',
      },
    ],
    spiritualManifestation: {
      practices: [
        {
          id: 'sp-301',
          type: 'ritual',
          title: '晨间身体感激与呼吸仪式',
          detail: '晨起双手抚摸心脏与腹部，做5组深长腹式呼吸，感谢身体陪伴。',
          date: '2026-08-14',
        },
      ],
    },
    visionConnection: '身心强健',
    manifestationNarrative: '身体越来越通透有力，稳稳地扎根在现实大地上。',
    progressPercent: 85,
    status: 'active',
    createdAt: '2026-07-20',
  },
  {
    id: 'g-archived-1',
    title: '完成首套草药手作蜡烛产品线研发与打样',
    type: 'short_term',
    area: 'creation',
    parentId: 'g-2',
    timeframeType: 'exact',
    startDate: '2026-06-01',
    targetDate: '2026-07-15',
    reality: '完成4款草药香型调配、大豆蜡温控测试、定制瓶身贴纸与包装打样。',
    why: '打造自己的第一款实体交付产品，开启自给自足的商业闭环。',
    identity: '我是一个将美与灵性转化为真实产品的手作者。',
    coreBelief: '专注做好一件微小的事，宇宙会为真诚的创造敞开大门。',
    evidence: ['成功打样4款香型', '首批30个样品全部测试合格并获得好评'],
    visionConnection: '手作与灵性创造',
    manifestationNarrative: '创造从灵感诞生到物质世界落地，是一次完整的显化旅程。',
    progressPercent: 100,
    status: 'archived',
    archivedAt: '2026-07-20',
    trophy: {
      type: 'trophy',
      title: '🌟 首发产品显化先锋奖杯',
      citation: '恭喜你！在不确定性中勇敢迈出第一步，独立研发并完成了首套草药手作蜡烛产品线闭环，为自食其力筑下了第一块坚固的基石！',
      completedDate: '2026-07-20',
      icon: '🏆',
      personalReward: '犒劳自己一套心仪已久的天然植物精油套组',
    },
    createdAt: '2026-06-01',
  },
];

export const INITIAL_PATTERNS: TrajectoryPattern[] = [
  {
    id: 'pat-1',
    title: '关系不确定性 -> 注意力被转移',
    description: '当亲密对象回复延迟或态度不明确时，容易诱发背景焦虑，并下意识打乱正在进行的工作节奏。',
    triggerEvent: '未及时收到消息 / 暧昧对象态度模糊',
    observedLoop: '外界无回应 -> 自我怀疑 -> 频繁看手机 -> 工作中断 -> 懊恼',
    shiftSuggested: '将注意力锚定在身体感觉和手头创造物上，提醒自己：主动表达，但不负责两个人的关系。',
    firstObservedDate: '2026-07-25',
    lastObservedDate: '2026-08-14',
    frequencyCount: 6,
    lifeArea: 'relationship',
    trendStatus: 'improving',
  },
  {
    id: 'pat-2',
    title: '接受亲近之人帮助 -> 触发价值感防御',
    description: '当家人提供微小金钱或关怀时，可能下意识联想到家庭沉重历史，并将接受帮助等同于自我失败。',
    triggerEvent: '父母转账 / 给予关怀',
    observedLoop: '收到资助 -> 羞耻/难受 -> 紧绷抵触 -> 责怪自己不够争气',
    shiftSuggested: '尝试将金钱视为纯粹的爱的流动，允许自己被爱，把精力集中在当下的现金流建设上。',
    firstObservedDate: '2026-08-01',
    lastObservedDate: '2026-08-15',
    frequencyCount: 3,
    lifeArea: 'relationship',
    trendStatus: 'watch',
  },
  {
    id: 'pat-3',
    title: '微小具体交付 -> 迅速建立踏实感',
    description: '每当完成一个具体的蜡烛制作、播完一场直播或看完整篇文献，身心能量状态会迅速从虚浮转为踏实。',
    triggerEvent: '启动微小行动（制作一件产品 / 播完1场）',
    observedLoop: '启动困难/轻微抗拒 -> 专注投入 -> 交付完成 -> 踏实充盈 -> 自信上升',
    shiftSuggested: '继续降低启动阻力，不求完美，依靠微小行动的正反馈驱动生活。',
    firstObservedDate: '2026-07-28',
    lastObservedDate: '2026-08-15',
    frequencyCount: 14,
    lifeArea: 'career',
    trendStatus: 'improving',
  },
];

export const INITIAL_EVENTS: LifeEvent[] = [
  {
    id: 'evt-101',
    date: '2026-08-15',
    time_start: '14:00',
    time_end: '16:00',
    duration_minutes: 120,
    duration_display: '2h',
    description: '直播2小时 (手作蜡烛与塔罗分享)',
    area: 'career',
    category: '收入 / 业务执行',
    subcategory: '直播',
    raw_note: '今天下午播了两个小时，状态挺顺的',
    confidence: 0.98,
    status: 'confirmed',
    associatedState: '踏实',
    interpretation: '稳定业务交付的现实证据，直接支撑现金流目标。',
  },
  {
    id: 'evt-102',
    date: '2026-08-15',
    time_start: '16:30',
    time_end: '17:30',
    duration_minutes: 60,
    duration_display: '1h',
    description: '为客户制作定制草药魔法蜡烛',
    area: 'career',
    category: '客户交付',
    subcategory: '手工蜡烛',
    raw_note: '然后给客户做了一个蜡烛',
    confidence: 0.95,
    status: 'confirmed',
    associatedState: '专注',
    interpretation: '高价值感的手作创造，闭环交付。',
  },
  {
    id: 'evt-103',
    date: '2026-08-15',
    time_start: '11:00',
    time_end: '12:00',
    duration_minutes: 60,
    duration_display: '1h',
    description: '健身房力量训练 (臀腿与拉伸)',
    area: 'health',
    category: '力量训练',
    subcategory: '健身',
    raw_note: '上午去健身房练了腿，挺累但踏实',
    confidence: 0.92,
    status: 'confirmed',
    associatedState: '踏实',
    interpretation: '身心能量筑基，落实当下。',
  },
  {
    id: 'evt-104',
    date: '2026-08-15',
    description: '母亲转账 100 元',
    area: 'relationship',
    category: '家庭',
    subcategory: '父母互动',
    amount: 100,
    duration_display: '未知',
    raw_note: '妈妈给了我100块，我突然特别难受',
    confidence: 0.95,
    status: 'needs_time_confirm',
    associatedState: '被触发',
    interpretation: '触碰了对家庭经济匮乏的记忆与自我价值焦虑。',
  },
  {
    id: 'evt-105',
    date: '2026-08-15',
    description: '英语播客精听与笔记 (35分钟)',
    area: 'growth',
    category: '语言学习',
    subcategory: '英语听力',
    duration_minutes: 35,
    duration_display: '35min',
    raw_note: '看了英语播客40分钟左右',
    confidence: 0.9,
    status: 'confirmed',
    associatedState: '平静',
    interpretation: '长期认知复利积累。',
  },
  // Past days events
  {
    id: 'evt-091',
    date: '2026-08-14',
    time_start: '15:00',
    time_end: '17:00',
    duration_minutes: 120,
    duration_display: '2h',
    description: '直播2小时 (手作产品介绍)',
    area: 'career',
    category: '业务执行',
    subcategory: '直播',
    raw_note: '播了2小时',
    confidence: 0.95,
    status: 'confirmed',
  },
  {
    id: 'evt-092',
    date: '2026-08-14',
    duration_minutes: 45,
    duration_display: '45min',
    description: '深度冥想与呼吸练习',
    area: 'health',
    category: '身心恢复',
    subcategory: '冥想',
    raw_note: '做了个冥想',
    confidence: 0.9,
    status: 'confirmed',
  },
  {
    id: 'evt-093',
    date: '2026-08-14',
    duration_minutes: 50,
    duration_display: '50min',
    description: '研读神秘学草药文献',
    area: 'growth',
    category: '专业学习',
    subcategory: '神秘学',
    raw_note: '读了点草药学的资料',
    confidence: 0.92,
    status: 'confirmed',
  },
  {
    id: 'evt-081',
    date: '2026-08-13',
    duration_minutes: 90,
    duration_display: '1.5h',
    description: '完成2位客户的线上塔罗咨询',
    area: 'career',
    category: '咨询交付',
    subcategory: '塔罗',
    amount: 300,
    raw_note: '做了两个占卜咨询',
    confidence: 0.95,
    status: 'confirmed',
  },
  {
    id: 'evt-082',
    date: '2026-08-13',
    duration_minutes: 60,
    duration_display: '1h',
    description: '房间大扫除与空间熏香净化',
    area: 'life',
    category: '家务整理',
    subcategory: '打扫',
    raw_note: '把家里里外外打扫了一遍',
    confidence: 0.9,
    status: 'confirmed',
  },
];

export const INITIAL_STATES: LifeState[] = [
  {
    id: 'st-101',
    date: '2026-08-15',
    timestamp: '10:15',
    primaryMood: '平静',
    energyLevel: 3,
    contextDescription: '自然醒来，准备开启一天',
    rawNote: '今天十点醒的',
    innerCompassAligned: true,
  },
  {
    id: 'st-102',
    date: '2026-08-15',
    timestamp: '12:10',
    primaryMood: '踏实',
    energyLevel: 4,
    contextDescription: '完成健身房力量训练',
    rawNote: '刚去健身房回来',
    innerCompassAligned: true,
  },
  {
    id: 'st-103',
    date: '2026-08-15',
    timestamp: '13:20',
    primaryMood: '被触发',
    energyLevel: 2,
    contextDescription: '收到母亲转账产生自尊与匮乏感冲突',
    rawNote: '妈妈给我100元，我不知道为什么突然特别难受',
    innerCompassAligned: false,
  },
  {
    id: 'st-104',
    date: '2026-08-15',
    timestamp: '16:05',
    primaryMood: '有动力',
    energyLevel: 4,
    contextDescription: '直播顺利完成，情绪未阻碍行动',
    rawNote: '今天直播居然挺顺',
    innerCompassAligned: true,
  },
  {
    id: 'st-105',
    date: '2026-08-15',
    timestamp: '18:00',
    primaryMood: '焦虑',
    energyLevel: 2,
    contextDescription: '对方未回复消息引发轻微烦躁',
    rawNote: '那个男生又没回消息，我有点烦',
    innerCompassAligned: false,
  },
];

export const INITIAL_DAILY_REVIEWS: DailyReview[] = [
  {
    id: 'rev-0814',
    date: '2026-08-14',
    eventsSummary: [
      '完成下午 2 小时直播，主要展示了手作蜡烛新品与使用技巧。',
      '完成 45 分钟深度冥想与呼吸练习，舒缓神经系统。',
      '研读神秘学草药学文献 50 分钟，做好复盘笔记。',
    ],
    successes: [
      '在身体稍显困顿的午后，依然准时开启了直播并保持了高专注度。',
      '没有因为外界琐事分散注意力，持续在专业学习上投入深度时间。',
    ],
    gratitudes: [
      '感谢自己的专注力在逐渐恢复。',
      '感谢植物草药赋予我的安宁与灵感。',
    ],
    integrations: [
      '情绪疲劳 -> 过去常选择刷手机逃避 -> 今天选择了呼吸冥想 -> 能量在40分钟内平稳恢复。',
    ],
    blindSpots: [
      '可能在潜意识中仍将“休息”误解为“不务正业”，值得继续观察并学会心安理得地深度恢复。',
    ],
    goalConnections: [
      '直播与专业文献积累，正在强化“我是一个能够独立创造价值的手作践行者”的身份认知。',
    ],
    manifestationNarrative:
      '一切都在以正确的节拍展开。你不再通过焦虑驱使自己，而是通过稳定的节奏与丰盛的世界共振。',
    innerCompass: {
      bodyWilling: true,
      heartPeaceful: true,
      proactiveChoice: true,
      facingReality: true,
      moreComplete: true,
      alignmentScore: 9,
      reflectionNotes: '身心极为一致，步调稳健。',
    },
    confirmedData: true,
    createdAt: '2026-08-14T22:30:00Z',
  },
];

export const INITIAL_KNOWLEDGE_ITEMS = [
  {
    id: 'know-1',
    title: '不配得感与金钱流动的能量视角',
    category: 'belief' as const,
    source: 'mentor_synthesis' as const,
    content:
      '金钱本质是创造价值后的能量流动，而不是对苦难与牺牲的道德奖赏。过去来自家庭的情绪负债容易让你在收钱时产生内疚感，重构信念：“我是在诚实交付我的心血与智慧，收钱是彼此能量的平衡与尊重”。',
    tags: ['金钱观', '深层信念', '情绪剥离'],
    createdAt: '2026-08-10',
  },
  {
    id: 'know-2',
    title: '第一序改变 vs 第二序改变 (Second-Order Change)',
    category: 'mental_model' as const,
    source: 'user_note' as const,
    content:
      '第一序改变：在原有系统内做加法或消耗自己（比如更拼命、更焦虑地发消息、强迫自己更痛苦地死撑）。第二序改变：跳出原有系统的底层规则，重构自我的身份定位与反应模式（比如在焦虑时停止盲动，回到自己的节奏，用结构化行动代替情绪宣泄）。',
    tags: ['思维模型', '心理学', '系统论'],
    createdAt: '2026-08-12',
  },
  {
    id: 'know-3',
    title: '情绪与行动的完全剥离模型',
    category: 'strategy' as const,
    source: 'review_insight' as const,
    content:
      '感到低落、疲惫、被关系触发是身体与神经系统的自然反应，允许它们像天气一样存在；但我依然可以在身体里留出空间，准时完成今天计划的2小时工作。行动不依赖于情绪完美的准备。',
    tags: ['情绪管理', '行动力', '自我一致性'],
    createdAt: '2026-08-14',
  },
];

export const INITIAL_TODOS: TodoItem[] = [
  {
    id: 'todo-1',
    date: '2026-08-15',
    title: '晚上 20:00-22:00 专场直播2小时 (手作蜡烛解密与咨询互动)',
    completed: false,
    area: 'career',
    estimatedMinutes: 120,
    priority: 'high',
    createdAt: '2026-08-15T09:00:00Z',
  },
  {
    id: 'todo-2',
    date: '2026-08-15',
    title: '复盘本周客户咨询案例，归纳手作草药配方卡片',
    completed: false,
    area: 'creation',
    estimatedMinutes: 45,
    priority: 'medium',
    createdAt: '2026-08-15T09:15:00Z',
  },
  {
    id: 'todo-3',
    date: '2026-08-15',
    title: '睡前听 20 分钟英语商业与心理播客',
    completed: false,
    area: 'growth',
    estimatedMinutes: 20,
    priority: 'low',
    createdAt: '2026-08-15T09:30:00Z',
  },
  {
    id: 'todo-4',
    date: '2026-08-15',
    title: '给昨天预定定制仪式蜡烛的客户打包并安排顺丰寄出',
    completed: true,
    completedAt: '2026-08-15T15:30:00Z',
    area: 'career',
    estimatedMinutes: 30,
    priority: 'high',
    convertedToEventId: 'evt-today-1',
    createdAt: '2026-08-15T08:30:00Z',
  },
  {
    id: 'todo-5',
    date: '2026-08-15',
    title: '下午健身房臀腿力量训练与全身拉伸',
    completed: true,
    completedAt: '2026-08-15T17:15:00Z',
    area: 'health',
    estimatedMinutes: 60,
    priority: 'high',
    convertedToEventId: 'evt-today-2',
    createdAt: '2026-08-15T08:30:00Z',
  },
];

export const INITIAL_FOCUS_ITEMS = [
  {
    id: 'focus-1',
    text: '完成下午 2 小时手作蜡烛定制与客户交付',
    completed: true,
    createdAt: '2026-08-15T08:30:00Z',
  },
  {
    id: 'focus-2',
    text: '健身房臀腿力量训练 40 分钟',
    completed: false,
    createdAt: '2026-08-15T08:30:00Z',
  },
  {
    id: 'focus-3',
    text: '晚上做 10 分钟未来视觉化显化与日结',
    completed: false,
    createdAt: '2026-08-15T08:30:00Z',
  },
];

